on:  
  push:
    branches:
      - 'develop'

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
        #   token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: npm run install:all
      - run: npm version patch
      - run: git push --tags
      - name: Package extension
        uses: lannonbr/vsce-action@3.0.0
        with:
          args: "package"
      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.vsix
          draft: true
      # - uses: lannonbr/vsce-action@3.0.0
      #   with:
      #     args: "publish -p $VSCE_TOKEN"
      #   env:
      #     VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
