on:  
  push:
    branches:
      - 'main'

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm run install:all:ci
      - name: Release
        env:
          HUSKY: 0
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx semantic-release
      - id: versionSet
        run: echo "tag_name=v"$(cat $VERSION_FILE)"" >> "$GITHUB_OUTPUT"
